Java compute Build Failed
googleapis/java-compute pull request #219
Opened 2020-09-28 14:03 UTC by twinkle-kadia

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-compute/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Fixes #200

2020-10-27 22:25 UTC, chingor13 requested changes

2020-10-27 22:25 UTC, chingor13 commented on src/test/java/com/google/cloud/compute/v1/it/BaseTest.java
> -    Timestamp cutoff = Timestamp.of(calendar.getTime());
This `cleanUpNetworks` was here to delete old networks that are not cleaned up in previous test runs. We have a hard limit of ~10 networks on the project which cannot be changed.

2020-11-17 23:42 UTC, stephaniewang526 commented
@twinkle-kadia could you please take a look at this? This is blocking the release. Thank you!

2021-10-06 21:38 UTC, chanseokoh commented
#200 is closed. This seems unnecessary.

2021-10-06 21:38 UTC, closed without merging